---
title: "Steak Data Project Doc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(fivethirtyeight)
library(dplyr)
library(moderndive)
library(broom)
```

```{r}
steak_survey <-
  steak_survey %>% 
  mutate(age = fct_relevel(as.character(age), "> 60", after = Inf),
         hhold_income = fct_relevel(as.character(hhold_income),
                                     "$0 - $24,999",
                                     "$25,000 - $49,999",
                                     "$50,000 - $99,999"),
         steak_prep_rare = ifelse(steak_prep %in% c("Rare", "Medium rare"),
                                    1, 0)) %>% 
  drop_na(steak_prep)
```

Response Variable: steak_prep

Predictor Variables: Region of US, Household Income, Gambling, Age

Interaction Effects Between: 
Age + Income
Gambling + Income
Region + Income
Region + Age


Question: Which factors most influence people to choose rare or medium rare steak over medium and well-done?

Here are some exploratory graphs:

```{r}
steak_survey %>% 
  ggplot() + 
  geom_bar(aes(x = steak_prep_rare, fill = steak_prep)) +
  facet_wrap(~region) +
  theme_minimal()
```

```{r}
steak_survey %>% 
  ggplot() + 
  geom_bar(aes(x = steak_prep_rare, fill = steak_prep_rare), )+
  facet_wrap(~hhold_income) +
  theme_minimal()
```



```{r}
lm_ageincome <- lm(steak_prep ~ age + hhold_income, data = steak_survey)
```



```{r}
glm_incomegamble <- glm(steak_prep_rare ~ gamble + hhold_income, data = steak_survey, family = binomial(link = "logit"))

tidy(glm_incomegamble)

glm_incomegamble %>%
  ggplot() +
  geom_bar(mapping = aes(x = steak_prep_rare, fill = hhold_income), position = "fill")+
  facet_wrap(~gamble)

```


```{r}
lm_regincome <- lm(steak_prep ~ region + hhold_income, data = steak_survey)
get_regression_table(lm_regincome)
```


```{r}
lm_regage <- lm(steak_prep ~ region + age, data = steak_survey)
get_regression_table(lm_regage)
```

```{r}
lm_regage %>% 
  ggplot(aes(x = age, y = steak_prep, color = region)) +
  geom_jitter()
```

